" Don't care about vi
set nocompatible
" Don't want anything I didn't write to be run
set modelines=0

" Theme
syntax enable
set background=dark
colorscheme Tomorrow-Night

" Indentation
filetype plugin indent on
set autoindent
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab

" Search options
set ignorecase
set smartcase

" Display options
set number
set showmode
set showcmd

" Interaction options
au FocusLost * :wa
set mouse=a

" Gvim display options
set guioptions-=T  " remove toolbar
set guioptions-=r  " remove right-hand scroll bar
set guioptions-=L  " remove left-hand scroll bar

" Put all files generated by vim in ~/.vim/ dir
if isdirectory($HOME . '/.vim/backup') == 0
 :silent !mkdir -p ~/.vim/backup >/dev/null 2>&1
endif
set backupdir=~/.vim/backup/
set backup

if isdirectory($HOME . '/.vim/swap') == 0
 :silent !mkdir -p ~/.vim/swap >/dev/null 2>&1
endif
set directory=~/.vim/swap//

set viminfo+=n~/.vim/viminfo

set undofile
if isdirectory($HOME . '/.vim/undo') == 0
 :silent !mkdir -p ~/.vim/undo > /dev/null 2>&1
endif
set undodir=~/.vim/undo//

" Vmux shortcuts
nnoremap <leader>r :VmuxSendPrimary bottom-left up<enter>
nnoremap <leader>gs :VmuxSendSecondary bottom-right git space status<enter>

" Ycm shortcuts
nnoremap <leader>fi :YcmCompleter FixIt<enter>
